const other = [
  "assets/img/product-img/product-big-3.jpg",
  "assets/img/product-img/product-big-2.jpg",
  "assets/img/product-img/product-big-1.jpg",
];
const Products = [
  {
    id: 1,
    brand: "Mango",
    Gender: "Women",
    Category: "Dresses",
    Title: "Knot Front Mini Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 65,
    discount: 25,
    img: {
      Front: "assets/img/product-img/product-1.jpg",
      Hover: "assets/img/product-img/product-2.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 2,
    brand: "topshop",
    Gender: "Women",
    Category: "Dresses",
    Title: "Poplin Displaced Wrap Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 80,
    discount: 30,
    img: {
      Front: "assets/img/product-img/product-3.jpg",
      Hover: "assets/img/product-img/product-4.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 3,
    brand: "topshop",
    Gender: "Women",
    Category: "Dresses",
    Title: "Poplin Displaced Wrap Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 75,
    discount: 15,
    img: {
      Front: "assets/img/product-img/product-5.jpg",
      Hover: "assets/img/product-img/product-6.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 4,
    brand: "topshop",
    Gender: "Women",
    Category: "Dresses",
    Title: "PETITE Crepe Wrap Mini Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 80,
    discount: 30,
    img: {
      Front: "assets/img/product-img/product-7.jpg",
      Hover: "assets/img/product-img/product-8.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 5,
    brand: "topshop",
    Gender: "Women",
    Category: "Dresses",
    Title: "PETITE Belted Jumper Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 90,
    discount: 10,
    img: {
      Front: "assets/img/product-img/product-9.jpg",
      Hover: "assets/img/product-img/product-8.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 6,
    brand: "Zara",
    Gender: "Women",
    Category: "Dresses",
    Title: "PETITE Belted Jumper Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 25,
    discount: 0,
    img: {
      Front: "assets/img/product-img/a1.jpg",
      Hover: "assets/img/product-img/a2.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 7,
    brand: "Boohoo",
    Gender: "Women",
    Category: "Bodysuits",
    Title: "PETITE Belted Jumper Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 15,
    discount: 0,
    img: {
      Front: "assets/img/product-img/b2.jpg",
      Hover: "assets/img/product-img/b1.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
  {
    id: 8,
    brand: "Zara",
    Gender: "Women",
    Category: "Bodysuits",
    Title: "PETITE Belted Jumper Dress",
    Description:
      "Mauris viverra cursus ante laoreet eleifend. Donec vel fringilla ante. Aenean finibus velit id urna vehicula, nec maximus est sollicitudin.",
    price: 10,
    discount: 0,
    img: {
      Front: "assets/img/product-img/c1.jpg",
      Hover: "assets/img/product-img/c2.jpg",
      Other: other,
    },
    Size: ["S", "M", "L", "XL", "XXL"],
    Colors: ["Red", "Black", "White", "Green"],
  },
];
export default Products;
